/*
Para los elementos de la tabla periódica, hacer que el simbolo coincida con alimentos cuyos nombres (o iniciales) coincidan con los símbolos de los elementos químicos.
Señalar los grupos y los periodos con números. Todos los elementos contendrán el mismo tipo de información, en el mismo orden y colocación como en la tabla real de la tabla periódica.
Agruparemos los alimentos según los principales grupos nutricionales y asignaremos un color específico a cada grupo para facilitar la distinción:
Grupos nutricionales: Proteínas, Frutas, Verduras, Pescados, Mariscos, Lácteos, Cereales, Legumbres, Frutos secos, Huevos, Carnes, Embutidos, Postres, Bebidas, Aceites, Otros.
En la tabla periódica, para cada elemento se muestra: Nombre del alimento, grupo nutricional, Valor nutricional, Beneficios, Riesgos, calorías, proteínas, grasas, carbohidratos, fibra, vitaminas y minerales.   
Asegurarse que los alimentos tengan un grupo nutricional asignado variado y no repetir más de 10 veces.
*/

const elementosComoAlimentos = [
    {
        "numeroAtomico": 1,
        "elemento": "Hidrógeno",
        "simbolo": "H",
        "grupo": 1,
        "periodo": 1,
        "nombreAlimento": "Harina",
        "descripcion": "Harina de maiz",
        "grupoNutricional": "Cereales",
        "valorNutricional": "1 g de proteínas, 0.1 g de grasas, 5 g de carbohidratos, 2 g de fibra, 20 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 20,
        "proteinas": 1,
        "grasas": 0.1,
        "carbohidratos": 5,
        "fibra": 2,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"        
    },
    {"periodo": 1},{"periodo": 1},{"periodo": 1},
    {"periodo": 1},{"periodo": 1},{"periodo": 1},
    {"periodo": 1},{"periodo": 1},{"periodo": 1},
    {"periodo": 1},{"periodo": 1},{"periodo": 1},
    {"periodo": 1},{"periodo": 1},{"periodo": 1},
    {"periodo": 1},
    {
        "numeroAtomico": 2,
        "elemento": "Helio",
        "simbolo": "He",
        "grupo": 18,
        "periodo": 1,
        "nombreAlimento": "Helado",
        "descripcion": "Postre frío y dulce",
        "grupoNutricional": "Postres",
        "valorNutricional": "300-500 kcal por 100 g (varía según los ingredientes), alto en carbohidratos y azúcares",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 3,
        "elemento": "Litio",
        "simbolo": "Li",
        "grupo": 1,
        "periodo": 2,
        "nombreAlimento": "Limón",
        "grupoNutricional": "Frutas",
        "valorNutricional": "0.5 g de proteínas, 0.3 g de grasas, 14 g de carbohidratos, 2 g de fibra, 74 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 74,
        "proteinas": 0.5,
        "grasas": 0.3,
        "carbohidratos": 14,
        "fibra": 2,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 4,
        "elemento": "Berilio",
        "simbolo": "Be",
        "grupo": 2,
        "periodo": 2,
        "nombreAlimento": "Berenjena",
        "grupoNutricional": "Verduras",
        "valorNutricional": "1 g de proteínas, 0.2 g de grasas, 6 g de carbohidratos, 3 g de fibra, 25 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 25,
        "proteinas": 1,
        "grasas": 0.2,
        "carbohidratos": 6,
        "fibra": 3,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {"periodo": 2},{"periodo": 2},{"periodo": 2},
    {"periodo": 2},{"periodo": 2},{"periodo": 2},
    {"periodo": 2},{"periodo": 2},{"periodo": 2},
    {"periodo": 2},
    {
        "numeroAtomico": 5,
        "elemento": "Boro",
        "simbolo": "B",
        "grupo": 13,
        "periodo": 2,
        "nombreAlimento": "Berberechos",
        "grupoNutricional": "Mariscos",
        "valorNutricional": "10 g de proteínas, 5 g de grasas, 0 g de carbohidratos, 0 g de fibra, 100 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 100,
        "proteinas": 10,
        "grasas": 5,
        "carbohidratos": 0,
        "fibra": 0,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"    
    },
    {
        "numeroAtomico": 6,
        "elemento": "Carbono",
        "simbolo": "C",
        "grupo": 14,
        "periodo": 2,
        "nombreAlimento": "Cebolla",
        "grupoNutricional": "Verduras",
        "valorNutricional": "1 g de proteínas, 0.1 g de grasas, 5 g de carbohidratos, 2 g de fibra, 20 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 20,
        "proteinas": 1,
        "grasas": 0.1,
        "carbohidratos": 5,
        "fibra": 2,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 7,
        "elemento": "Nitrógeno",
        "simbolo": "N",
        "grupo": 15,
        "periodo": 2,
        "nombreAlimento": "Naranja",
        "grupoNutricional": "Frutas",
        "valorNutricional": "1 g de proteínas, 0.2 g de grasas, 10 g de carbohidratos, 3 g de fibra, 50 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 50,
        "proteinas": 1,
        "grasas": 0.2,
        "carbohidratos": 10,
        "fibra": 3,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 8,
        "elemento": "Oxígeno",
        "simbolo": "O",
        "grupo": 16,
        "periodo": 2,
        "nombreAlimento": "Opuntia",
        "grupoNutricional": "Frutas",
        "valorNutricional": "1 g de proteínas, 0.2 g de grasas, 10 g de carbohidratos, 3 g de fibra, 50 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 50,
        "proteinas": 1,
        "grasas": 0.2,
        "carbohidratos": 10,
        "fibra": 3,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 9,
        "elemento": "Flúor",
        "simbolo": "F",
        "grupo": 17,
        "periodo": 2,
        "nombreAlimento": "Fresa",
        "grupoNutricional": "Frutas",
        "valorNutricional": "1 g de proteínas, 0.2 g de grasas, 10 g de carbohidratos, 3 g de fibra, 50 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 50,
        "proteinas": 1,
        "grasas": 0.2,
        "carbohidratos": 10,
        "fibra": 3,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"        
    },
    {
        "numeroAtomico": 10,
        "elemento": "Neón",
        "simbolo": "Ne",
        "grupo": 18,
        "periodo": 2,
        "nombreAlimento": "Nuez",
        "grupoNutricional": "Frutos secos",
        "valorNutricional": "5 g de proteínas, 10 g de grasas, 2 g de carbohidratos, 1 g de fibra, 150 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"        
    },
    {
        "numeroAtomico": 11,
        "elemento": "Sodio",
        "simbolo": "Na",
        "grupo": 1,
        "periodo": 3,
        "nombreAlimento": "Nabo",
        "grupoNutricional": "Verduras",
        "valorNutricional": "1 g de proteínas, 0.1 g de grasas, 5 g de carbohidratos, 2 g de fibra, 20 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 20,
        "proteinas": 1,
        "grasas": 0.1,
        "carbohidratos": 5,
        "fibra": 2,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 12,
        "elemento": "Magnesio",
        "simbolo": "Mg",
        "grupo": 2,
        "periodo": 3,
        "nombreAlimento": "Mango",
        "grupoNutricional": "Frutas",
        "valorNutricional": "1 g de proteínas, 0.2 g de grasas, 10 g de carbohidratos, 3 g de fibra, 50 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 50,
        "proteinas": 1,
        "grasas": 0.2,
        "carbohidratos": 10,
        "fibra": 3,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"        
    },
    {"periodo": 3},{"periodo": 3},{"periodo": 3},
    {"periodo": 3},{"periodo": 3},{"periodo": 3},
    {"periodo": 3},{"periodo": 3},{"periodo": 3},
    {"periodo": 3},
    {
        "numeroAtomico": 13,
        "elemento": "Aluminio",
        "simbolo": "Al",
        "grupo": 13,
        "periodo": 3,
        "nombreAlimento": "Almendra",
        "grupoNutricional": "Frutos secos",
        "valorNutricional": "5 g de proteínas, 10 g de grasas, 2 g de carbohidratos, 1 g de fibra, 150 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"        
    },
    {
        "numeroAtomico": 14,
        "elemento": "Silicio",
        "simbolo": "Si",
        "grupo": 14,
        "periodo": 3,
        "nombreAlimento": "Salmón",
        "grupoNutricional": "Pescados",
        "valorNutricional": "20 g de proteínas, 5 g de grasas, 0 g de carbohidratos, 0 g de fibra, 120 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 120,
        "proteinas": 20,
        "grasas": 5,
        "carbohidratos": 0,
        "fibra": 0,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"        
    },
    {
        "numeroAtomico": 15,
        "elemento": "Fósforo",
        "simbolo": "P",
        "grupo": 15,
        "periodo": 3,
        "nombreAlimento": "Pera",
        "grupoNutricional": "Frutas",
        "valorNutricional": "1 g de proteínas, 0.2 g de grasas, 10 g de carbohidratos, 3 g de fibra, 50 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 50,
        "proteinas": 1,
        "grasas": 0.2,
        "carbohidratos": 10,
        "fibra": 3,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"        
    },
    {
        "numeroAtomico": 16,
        "elemento": "Azufre",
        "simbolo": "S",
        "grupo": 16,
        "periodo": 3,
        "nombreAlimento": "Sandía",
        "grupoNutricional": "Frutas",
        "valorNutricional": "1 g de proteínas, 0.2 g de grasas, 10 g de carbohidratos, 3 g de fibra, 50 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 50,
        "proteinas": 1,
        "grasas": 0.2,
        "carbohidratos": 10,
        "fibra": 3,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"        
    },
    {
        "numeroAtomico": 17,
        "elemento": "Cloro",
        "simbolo": "Cl",
        "grupo": 17,
        "periodo": 3,
        "nombreAlimento": "Ciruela",
        "grupoNutricional": "Frutas",
        "valorNutricional": "1 g de proteínas, 0.2 g de grasas, 10 g de carbohidratos, 3 g de fibra, 50 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 50,
        "proteinas": 1,
        "grasas": 0.2,
        "carbohidratos": 10,
        "fibra": 3,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"        
    },
    {
        "numeroAtomico": 18,
        "elemento": "Argón",
        "simbolo": "Ar",
        "grupo": 18,
        "periodo": 3,
        "nombreAlimento": "Arándano",
        "grupoNutricional": "Frutas",
        "valorNutricional": "1 g de proteínas, 0.2 g de grasas, 10 g de carbohidratos, 3 g de fibra, 50 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 50,
        "proteinas": 1,
        "grasas": 0.2,
        "carbohidratos": 10,
        "fibra": 3,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"        
    },
    {
        "numeroAtomico": 19,
        "elemento": "Potasio",
        "simbolo": "K",
        "grupo": 1,
        "periodo": 4,
        "nombreAlimento": "Kiwi",
        "grupoNutricional": "Frutas",
        "valorNutricional": "1 g de proteínas, 0.2 g de grasas, 10 g de carbohidratos, 3 g de fibra, 50 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 50,
        "proteinas": 1,
        "grasas": 0.2,
        "carbohidratos": 10,
        "fibra": 3,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 20,
        "elemento": "Calcio",
        "simbolo": "Ca",
        "grupo": 2,
        "periodo": 4,
        "nombreAlimento": "Cacahuate",
        "grupoNutricional": "Frutos secos",
        "valorNutricional": "5 g de proteínas, 10 g de grasas, 2 g de carbohidratos, 1 g de fibra, 150 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 21,
        "elemento": "Escandio",
        "simbolo": "Sc",
        "grupo": 3,
        "periodo": 4,
        "nombreAlimento": "Espinaca",
        "grupoNutricional": "Verduras",
        "valorNutricional": "1 g de proteínas, 0.1 g de grasas, 5 g de carbohidratos, 2 g de fibra, 20 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 20,
        "proteinas": 1,
        "grasas": 0.1,
        "carbohidratos": 5,
        "fibra": 2,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 22,
        "elemento": "Titanio",
        "simbolo": "Ti",
        "grupo": 4,
        "periodo": 4,
        "nombreAlimento": "Tilapia",
        "grupoNutricional": "Pescados",
        "valorNutricional": "20 g de proteínas, 5 g de grasas, 0 g de carbohidratos, 0 g de fibra, 120 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 120,
        "proteinas": 20,
        "grasas": 5,
        "carbohidratos": 0,
        "fibra": 0,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"       
    },
    {
        "numeroAtomico": 23,
        "elemento": "Vanadio",
        "simbolo": "V",
        "grupo": 5,
        "periodo": 4,
        "nombreAlimento": "Vainilla",
        "grupoNutricional": "Dulces",
        "valorNutricional": "1 g de proteínas, 0.2 g de grasas, 10 g de carbohidratos, 3 g de fibra, 50 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 50,
        "proteinas": 1,
        "grasas": 0.2,
        "carbohidratos": 10,
        "fibra": 3,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 24,
        "elemento": "Cromo",
        "simbolo": "Cr",
        "grupo": 6,
        "periodo": 4,
        "nombreAlimento": "Cereza",
        "grupoNutricional": "Frutas",
        "valorNutricional": "1 g de proteínas, 0.2 g de grasas, 10 g de carbohidratos, 3 g de fibra, 50 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 50,
        "proteinas": 1,
        "grasas": 0.2,
        "carbohidratos": 10,
        "fibra": 3,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 25,
        "elemento": "Manganeso",
        "simbolo": "Mn",
        "grupo": 7,
        "periodo": 4,
        "nombreAlimento": "Mantequilla", 
        "grupoNutricional": "Lácteos",
        "valorNutricional": "5 g de proteínas, 10 g de grasas, 2 g de carbohidratos, 1 g de fibra, 150 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 26,
        "elemento": "Hierro",
        "simbolo": "Fe",
        "grupo": 8,
        "periodo": 4,
        "nombreAlimento": "Fenogreco",
        "descripcion": "Semillas de fenogreco",
        "grupoNutricional": "Legumbres",
        "valorNutricional": "5 g de proteínas, 10 g de grasas, 2 g de carbohidratos, 1 g de fibra, 150 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 27,
        "elemento": "Cobalto",
        "simbolo": "Co",
        "grupo": 9,
        "periodo": 4,
        "nombreAlimento": "Coliflor",
        "grupoNutricional": "Verduras",
        "valorNutricional": "1 g de proteínas, 0.1 g de grasas, 5 g de carbohidratos, 2 g de fibra, 20 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 20,
        "proteinas": 1,
        "grasas": 0.1,
        "carbohidratos": 5,
        "fibra": 2,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 28,
        "elemento": "Níquel",
        "simbolo": "Ni",
        "grupo": 10,
        "periodo": 4,
        "nombreAlimento": "Níscalo",
        "grupoNutricional": "Verduras",
        "valorNutricional": "1 g de proteínas, 0.1 g de grasas, 5 g de carbohidratos, 2 g de fibra, 20 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 20,
        "proteinas": 1,
        "grasas": 0.1,
        "carbohidratos": 5,
        "fibra": 2,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 29,
        "elemento": "Cobre",
        "simbolo": "Cu",
        "grupo": 11,
        "periodo": 4,
        "nombreAlimento": "Cúrcuma",
        "grupoNutricional": "Especias",
        "valorNutricional": "1 g de proteínas, 0.2 g de grasas, 10 g de carbohidratos, 3 g de fibra, 50 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 50,
        "proteinas": 1,
        "grasas": 0.2,
        "carbohidratos": 10,
        "fibra": 3,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 30,
        "elemento": "Zinc",
        "simbolo": "Zn",
        "grupo": 12,
        "periodo": 4,
        "nombreAlimento": "Zanahoria",
        "grupoNutricional": "Verduras",
        "valorNutricional": "1 g de proteínas, 0.1 g de grasas, 5 g de carbohidratos, 2 g de fibra, 20 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 20,
        "proteinas": 1,
        "grasas": 0.1,
        "carbohidratos": 5,
        "fibra": 2,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 31,
        "elemento": "Galio",
        "simbolo": "Ga",
        "grupo": 13,
        "periodo": 4,
        "nombreAlimento": "Garbanzos",
        "grupoNutricional": "Legumbres",
        "valorNutricional": "5 g de proteínas, 10 g de grasas, 2 g de carbohidratos, 1 g de fibra, 150 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 32,
        "elemento": "Germanio",
        "simbolo": "Ge",
        "grupo": 14,
        "periodo": 4,
        "nombreAlimento": "Gelatina",
        "grupoNutricional": "Postres",
        "valorNutricional": "5 g de proteínas, 10 g de grasas, 2 g de carbohidratos, 1 g de fibra, 150 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 33,
        "elemento": "Arsénico",
        "simbolo": "As",
        "grupo": 15,
        "periodo": 4,
        "nombreAlimento": "Pastel",
        "grupoNutricional": "Postres",
        "valorNutricional": "300-500 kcal por 100 g (varía según los ingredientes), alto en carbohidratos y azúcares",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 34,
        "elemento": "Selenio",
        "simbolo": "Se",
        "grupo": 16,
        "periodo": 4,
        "nombreAlimento": "Sésamo",
        "grupoNutricional": "Frutos secos",
        "valorNutricional": "5 g de proteínas, 10 g de grasas, 2 g de carbohidratos, 1 g de fibra, 150 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 35,
        "elemento": "Bromo",
        "simbolo": "Br",
        "grupo": 17,
        "periodo": 4,
        "nombreAlimento": "Brócoli",
        "grupoNutricional": "Verduras",
        "valorNutricional": "1 g de proteínas, 0.1 g de grasas, 5 g de carbohidratos, 2 g de fibra, 20 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 20,
        "proteinas": 1,
        "grasas": 0.1,
        "carbohidratos": 5,
        "fibra": 2,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 36,
        "elemento": "Kriptón",
        "simbolo": "Kr",
        "grupo": 18,
        "periodo": 4,
        "nombreAlimento": "Krémes",
        "grupoNutricional": "Postres",
        "valorNutricional": "300-500 kcal por 100 g (varía según los ingredientes), alto en carbohidratos y azúcares",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 37,
        "elemento": "Rubidio",
        "simbolo": "Rb",
        "grupo": 1,
        "periodo": 5,
        "nombreAlimento": "Robalo",
        "grupoNutricional": "Pescados",
        "valorNutricional": "20 g de proteínas, 5 g de grasas, 0 g de carbohidratos, 0 g de fibra, 120 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 120,
        "proteinas": 20,
        "grasas": 5,
        "carbohidratos": 0,
        "fibra": 0,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 38,
        "elemento": "Estroncio",
        "simbolo": "Sr",
        "grupo": 2,
        "periodo": 5,
        "nombreAlimento": "Sardina",
        "grupoNutricional": "Pescados",
        "valorNutricional": "20 g de proteínas, 5 g de grasas, 0 g de carbohidratos, 0 g de fibra, 120 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 120,
        "proteinas": 20,
        "grasas": 5,
        "carbohidratos": 0,
        "fibra": 0,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 39,
        "elemento": "Itrio",
        "simbolo": "Y",
        "grupo": 3,
        "periodo": 5,
        "nombreAlimento": "Yogurt",
        "grupoNutricional": "Lácteos",
        "valorNutricional": "5 g de proteínas, 10 g de grasas, 2 g de carbohidratos, 1 g de fibra, 150 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 40,
        "elemento": "Circonio",
        "simbolo": "Zr",
        "grupo": 4,
        "periodo": 5,
        "nombreAlimento": "Zurito",
        "descripcion": "Cerveza pequeña",
        "grupoNutricional": "Bebidas",
        "valorNutricional": "100-200 kcal por 100 ml (varía según los ingredientes), alto en azúcares",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 41,
        "elemento": "Niobio",
        "simbolo": "Nb",
        "grupo": 5,
        "periodo": 5,
        "nombreAlimento": "Nebbiolo",
        "grupoNutricional": "Bebidas",
        "valorNutricional": "100-200 kcal por 100 ml (varía según los ingredientes), alto en azúcares",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"        
    },
    {
        "numeroAtomico": 42,
        "elemento": "Molibdeno",
        "simbolo": "Mo",
        "grupo": 6,
        "periodo": 5,
        "nombreAlimento": "Mojito",
        "grupoNutricional": "Bebidas",
        "valorNutricional": "100-200 kcal por 100 ml (varía según los ingredientes), alto en azúcares",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 43,
        "elemento": "Tecnecio",
        "simbolo": "Tc",
        "grupo": 7,
        "periodo": 5,
        "nombreAlimento": "Tacos",
        "grupoNutricional": "Comida rápida",
        "valorNutricional": "300-500 kcal por porción (varía según los ingredientes), alto en grasas y carbohidratos",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 44,
        "elemento": "Rutenio",
        "simbolo": "Ru",
        "grupo": 8,
        "periodo": 5,
        "nombreAlimento": "Rulas",
        "grupoNutricional": "Carnes",
        "valorNutricional": "20 g de proteínas, 5 g de grasas, 0 g de carbohidratos, 0 g de fibra, 120 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 120,
        "proteinas": 20,
        "grasas": 5,
        "carbohidratos": 0,
        "fibra": 0,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 45,
        "elemento": "Rodio",
        "simbolo": "Rh",
        "grupo": 9,
        "periodo": 5,
        "nombreAlimento": "Rhoast Beef",
        "grupoNutricional": "Carnes",
        "valorNutricional": "20 g de proteínas, 5 g de grasas, 0 g de carbohidratos, 0 g de fibra, 120 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 120,
        "proteinas": 20,
        "grasas": 5,
        "carbohidratos": 0,
        "fibra": 0,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"        
    },
    {
        "numeroAtomico": 46,
        "elemento": "Paladio",
        "simbolo": "Pd",
        "grupo": 10,
        "periodo": 5,
        "nombreAlimento": "Pudding",
        "grupoNutricional": "Postres",
        "valorNutricional": "300-500 kcal por porción (varía según los ingredientes), alto en grasas y carbohidratos",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"        
    },
    {
        "numeroAtomico": 47,
        "elemento": "Plata",
        "simbolo": "Ag",
        "grupo": 11,
        "periodo": 5,
        "nombreAlimento": "Agua",
        "grupoNutricional": "Bebidas",
        "valorNutricional": "0 kcal por 100 ml, sin grasas, carbohidratos ni proteínas",
        "beneficios": "Ayuda a la hidratación y a la digestión",
        "riesgos": "Puede causar ahogamiento",
        "calorias": 0,
        "proteinas": 0,
        "grasas": 0,
        "carbohidratos": 0,
        "fibra": 0,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 48,
        "elemento": "Cadmio",
        "simbolo": "Cd",
        "grupo": 12,
        "periodo": 5,
        "nombreAlimento": "Cordero",
        "grupoNutricional": "Carnes",
        "valorNutricional": "20 g de proteínas, 5 g de grasas, 0 g de carbohidratos, 0 g de fibra, 120 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 120,
        "proteinas": 20,
        "grasas": 5,
        "carbohidratos": 0,
        "fibra": 0,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 49,
        "elemento": "Indio",
        "simbolo": "In",
        "grupo": 13,
        "periodo": 5,
        "nombreAlimento": "Infusión",
        "grupoNutricional": "Bebidas",
        "valorNutricional": "0 kcal por 100 ml, sin grasas, carbohidratos ni proteínas",
        "beneficios": "Ayuda a la hidratación y a la digestión",
        "riesgos": "Puede causar ahogamiento, alergias o quemaduras",
        "calorias": 0,
        "proteinas": 0,
        "grasas": 0,
        "carbohidratos": 0,
        "fibra": 0,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 50,
        "elemento": "Estaño",
        "simbolo": "Sn",
        "grupo": 14,
        "periodo": 5,
        "nombreAlimento": "Sándwich",
        "grupoNutricional": "Comida rápida",
        "valorNutricional": "300-500 kcal por porción (varía según los ingredientes), alto en grasas y carbohidratos",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 51,
        "elemento": "Antimonio",
        "simbolo": "Sb",
        "grupo": 15,
        "periodo": 5,
        "nombreAlimento": "Sabana de res",
        "grupoNutricional": "Carnes",
        "valorNutricional": "20 g de proteínas, 5 g de grasas, 0 g de carbohidratos, 0 g de fibra, 120 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 120,
        "proteinas": 20,
        "grasas": 5,
        "carbohidratos": 0,
        "fibra": 0,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 52,
        "elemento": "Telurio",
        "simbolo": "Te",
        "grupo": 16,
        "periodo": 5,
        "nombreAlimento": "Té",
        "grupoNutricional": "Bebidas",
        "valorNutricional": "0 kcal por 100 ml, sin grasas, carbohidratos ni proteínas",
        "beneficios": "Ayuda a la hidratación y a la digestión",
        "riesgos": "Puede causar ahogamiento",
        "calorias": 0,
        "proteinas": 0,
        "grasas": 0,
        "carbohidratos": 0,
        "fibra": 0,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 53,
        "elemento": "Yodo",
        "simbolo": "I",
        "grupo": 17,
        "periodo": 5,
        "nombreAlimento": "Ichintal",
        "descripcion": "Fruta mexicana (raíz comestible de América Central)",
        "grupoNutricional": "Frutas",
        "valorNutricional": "1 g de proteínas, 0.2 g de grasas, 10 g de carbohidratos, 3 g de fibra, 50 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 50,
        "proteinas": 1,
        "grasas": 0.2,
        "carbohidratos": 10,
        "fibra": 3,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 54,
        "elemento": "Xenón",
        "simbolo": "Xe",
        "grupo": 18,
        "periodo": 5,
        "nombreAlimento": "Xoconostle",
        "grupoNutricional": "Frutas",
        "valorNutricional": "1 g de proteínas, 0.2 g de grasas, 10 g de carbohidratos, 3 g de fibra, 50 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 50,
        "proteinas": 1,
        "grasas": 0.2,
        "carbohidratos": 10,
        "fibra": 3,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 55,
        "elemento": "Cesio",
        "simbolo": "Cs",
        "grupo": 1,
        "periodo": 6,
        "nombreAlimento": "Costillas",
        "descripcion": "Costillas de cerdo",
        "grupoNutricional": "Carnes",
        "valorNutricional": "20 g de proteínas, 5 g de grasas, 0 g de carbohidratos, 0 g de fibra, 120 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 120,
        "proteinas": 20,
        "grasas": 5,
        "carbohidratos": 0,
        "fibra": 0,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"        
    },
    {
        "numeroAtomico": 56,
        "elemento": "Bario",
        "simbolo": "Ba",
        "grupo": 2,
        "periodo": 6,
        "nombreAlimento": "Bacalao",
        "grupoNutricional": "Pescados",
        "valorNutricional": "20 g de proteínas, 5 g de grasas, 0 g de carbohidratos, 0 g de fibra, 120 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 120,
        "proteinas": 20,
        "grasas": 5,
        "carbohidratos": 0,
        "fibra": 0,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {   "id":"*", 
        "elementos": "57-71",    
        "periodo": 6,
        "tipo": "Otros"
    },
    {
        "numeroAtomico": 72,
        "elemento": "Hafnio",
        "simbolo": "Hf",
        "grupo": 4,
        "periodo": 6,
        "nombreAlimento": "Huevos fritos",
        "grupoNutricional": "Carnes",
        "valorNutricional": "20 g de proteínas, 5 g de grasas, 0 g de carbohidratos, 0 g de fibra, 120 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 120,
        "proteinas": 20,
        "grasas": 5,
        "carbohidratos": 0,
        "fibra": 0,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 73,
        "elemento": "Tantalio",
        "simbolo": "Ta",
        "grupo": 5,
        "periodo": 6,
        "nombreAlimento": "Tacos",
        "descripcion": "Tacos de guisado",
        "grupoNutricional": "Comida rápida",
        "valorNutricional": "20 g de proteínas, 5 g de grasas, 0 g de carbohidratos, 0 g de fibra, 120 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 120,
        "proteinas": 20,
        "grasas": 5,
        "carbohidratos": 0,
        "fibra": 0,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 74,
        "elemento": "Wolframio",
        "simbolo": "W",
        "grupo": 6,
        "periodo": 6,
        "nombreAlimento": "Waffles",
        "grupoNutricional": "Postres",
        "valorNutricional": "300-500 kcal por porción (varía según los ingredientes), alto en grasas y carbohidratos",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 75,
        "elemento": "Renio",
        "simbolo": "Re",
        "grupo": 7,
        "periodo": 6,
        "nombreAlimento": "Requesón",
        "grupoNutricional": "Lácteos",
        "valorNutricional": "5 g de proteínas, 10 g de grasas, 2 g de carbohidratos, 1 g de fibra, 150 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 76,
        "elemento": "Osmio",
        "simbolo": "Os",
        "grupo": 8,
        "periodo": 6,
        "nombreAlimento": "Ostras",
        "grupoNutricional": "Mariscos",
        "valorNutricional": "20 g de proteínas, 5 g de grasas, 0 g de carbohidratos, 0 g de fibra, 120 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 120,
        "proteinas": 20,
        "grasas": 5,
        "carbohidratos": 0,
        "fibra": 0,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 77,
        "elemento": "Iridio",
        "simbolo": "Ir",
        "grupo": 9,
        "periodo": 6,
        "nombreAlimento": "Tiramisú",
        "grupoNutricional": "Postres",
        "valorNutricional": "300-500 kcal por porción (varía según los ingredientes), alto en grasas y carbohidratos",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 78,
        "elemento": "Platino",
        "simbolo": "Pt",
        "grupo": 10,
        "periodo": 6,
        "nombreAlimento": "Plátano",
        "grupoNutricional": "Frutas",
        "valorNutricional": "1 g de proteínas, 0.2 g de grasas, 10 g de carbohidratos, 3 g de fibra, 50 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 50,
        "proteinas": 1,
        "grasas": 0.2,
        "carbohidratos": 10,
        "fibra": 3,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 79,
        "elemento": "Oro",
        "simbolo": "Au",
        "grupo": 11,
        "periodo": 6,
        "nombreAlimento": "Au Gratin",
        "descripcion": "Papas gratinadas",
        "grupoNutricional": "Comida rápida",
        "valorNutricional": "300-500 kcal por porción (varía según los ingredientes), alto en grasas y carbohidratos",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 80,
        "elemento": "Mercurio",
        "simbolo": "Hg",
        "grupo": 12,
        "periodo": 6,
        "nombreAlimento": "Hamburguesa",
        "grupoNutricional": "Comida rápida",
        "valorNutricional": "300-500 kcal por porción (varía según los ingredientes), alto en grasas y carbohidratos",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"        
    },
    {
        "numeroAtomico": 81,
        "elemento": "Talio",
        "simbolo": "Tl",
        "grupo": 13,
        "periodo": 6,
        "nombreAlimento": "Tlayuda",
        "grupoNutricional": "Comida rápida",
        "valorNutricional": "300-500 kcal por porción (varía según los ingredientes), alto en grasas y carbohidratos",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 82,
        "elemento": "Plomo",
        "simbolo": "Pb",
        "grupo": 14,
        "periodo": 6,
        "nombreAlimento": "Peanut butter",
        "grupoNutricional": "Botanas",
        "valorNutricional": "100-200 kcal por porción (varía según los ingredientes), alto en grasas y carbohidratos",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 83,
        "elemento": "Bismuto",
        "simbolo": "Bi",
        "grupo": 15,
        "periodo": 6,
        "nombreAlimento": "Bisquets",
        "grupoNutricional": "Panadería",
        "valorNutricional": "100-200 kcal por porción (varía según los ingredientes), alto en grasas y carbohidratos",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 84,
        "elemento": "Polonio",
        "simbolo": "Po",
        "grupo": 16,
        "periodo": 6,
        "nombreAlimento": "Pollo",
        "grupoNutricional": "Carnes",
        "valorNutricional": "20 g de proteínas, 5 g de grasas, 0 g de carbohidratos, 0 g de fibra, 120 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 120,
        "proteinas": 20,
        "grasas": 5,
        "carbohidratos": 0,
        "fibra": 0,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },    
    {
        "numeroAtomico": 85,
        "elemento": "Astato",
        "simbolo": "At",
        "grupo": 17,
        "periodo": 6,
        "nombreAlimento": "Atún",
        "grupoNutricional": "Pescados",
        "valorNutricional": "20 g de proteínas, 5 g de grasas, 0 g de carbohidratos, 0 g de fibra, 120 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 120,
        "proteinas": 20,
        "grasas": 5,
        "carbohidratos": 0,
        "fibra": 0,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 86,
        "elemento": "Radón",
        "simbolo": "Rn",
        "grupo": 18,
        "periodo": 6,
        "nombreAlimento": "Ramen",
        "grupoNutricional": "Comida rápida",
        "valorNutricional": "300-500 kcal por porción (varía según los ingredientes), alto en grasas y carbohidratos",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 87,
        "elemento": "Francio",
        "simbolo": "Fr",
        "grupo": 1,
        "periodo": 7,
        "nombreAlimento": "Frijoles",
        "grupoNutricional": "Leguminosas",
        "valorNutricional": "5 g de proteínas, 10 g de grasas, 2 g de carbohidratos, 1 g de fibra, 150 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 88,
        "elemento": "Radio",
        "simbolo": "Ra",
        "grupo": 2,
        "periodo": 7,
        "nombreAlimento": "Ravioli",
        "grupoNutricional": "Pastas",
        "valorNutricional": "300-500 kcal por porción (varía según los ingredientes), alto en grasas y carbohidratos",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {   "id":"**", 
        "elementos": "89-103",    
        "periodo": 7,
        "tipo": "Actinidios"
    },
    {
        "numeroAtomico": 104,
        "elemento": "Rutherfordio",
        "simbolo": "Rf",
        "grupo": 4,
        "periodo": 7,
        "nombreAlimento": "Raffaello",
        "descripcion": "Raffaello (Dulce de coco y almendra)",
        "grupoNutricional": "Postres",
        "valorNutricional": "300-500 kcal por porción (varía según los ingredientes), alto en grasas y carbohidratos",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 105,
        "elemento": "Dubnio",
        "simbolo": "Db",
        "grupo": 5,
        "periodo": 7,
        "nombreAlimento": "Dublinesa",
        "descripcion": "Dublinesa (Pastel de chocolate)",
        "grupoNutricional": "Postres",
        "valorNutricional": "300-500 kcal por porción (varía según los ingredientes), alto en grasas y carbohidratos",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 106,
        "elemento": "Seaborgio",
        "simbolo": "Sg",
        "grupo": 6,
        "periodo": 7,
        "nombreAlimento": "Sopa garbanzo",
        "descripcion": "Sopa de garbanzo",
        "grupoNutricional": "Leguminosas",
        "valorNutricional": "5 g de proteínas, 10 g de grasas, 2 g de carbohidratos, 1 g de fibra, 150 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"        
    },
    {
        "numeroAtomico": 107,
        "elemento": "Bohrio",
        "simbolo": "Bh",
        "grupo": 7,
        "periodo": 7,
        "nombreAlimento": "Bohio",
        "descripcion": "Bohio (Fruto de la palma)",
        "grupoNutricional": "Frutas",
        "valorNutricional": "1 g de proteínas, 0.2 g de grasas, 10 g de carbohidratos, 3 g de fibra, 50 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 50,
        "proteinas": 1,
        "grasas": 0.2,
        "carbohidratos": 10,
        "fibra": 3,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 108,
        "elemento": "Hassio",
        "simbolo": "Hs",
        "grupo": 8,
        "periodo": 7,
        "nombreAlimento": "Whisky",
        "grupoNutricional": "Bebidas",
        "valorNutricional": "0 kcal por 100 ml, sin grasas, carbohidratos ni proteínas",
        "beneficios": "Ayuda a la hidratación y a la digestión",
        "riesgos": "Puede causar ahogamiento",
        "calorias": 0,
        "proteinas": 0,
        "grasas": 0,
        "carbohidratos": 0,
        "fibra": 0,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 109,
        "elemento": "Meitnerio",
        "simbolo": "Mt",
        "grupo": 9,
        "periodo": 7,
        "nombreAlimento": "Mantecadas",
        "grupoNutricional": "Panadería",
        "valorNutricional": "100-200 kcal por porción (varía según los ingredientes), alto en grasas y carbohidratos",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 110,
        "elemento": "Darmstatio",
        "simbolo": "Ds",
        "grupo": 10,
        "periodo": 7,
        "nombreAlimento": "Donas",
        "grupoNutricional": "Panadería",
        "valorNutricional": "100-200 kcal por porción (varía según los ingredientes), alto en grasas y carbohidratos",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 111,
        "elemento": "Roentgenio",
        "simbolo": "Rg",
        "grupo": 11,
        "periodo": 7,
        "nombreAlimento": "Rugelach",
        "descripcion": "Rugelach (Pastel de origen judío)",
        "grupoNutricional": "Panadería",
        "valorNutricional": "100-200 kcal por porción (varía según los ingredientes), alto en grasas y carbohidratos",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 112,
        "elemento": "Copernicio",
        "simbolo": "Cn",
        "grupo": 12,
        "periodo": 7,
        "nombreAlimento": "Conejo",
        "grupoNutricional": "Carnes",
        "valorNutricional": "20 g de proteínas, 5 g de grasas, 0 g de carbohidratos, 0 g de fibra, 120 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 120,
        "proteinas": 20,
        "grasas": 5,
        "carbohidratos": 0,
        "fibra": 0,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"        
    },
    {
        "numeroAtomico": 113,
        "elemento": "Nihonio",
        "simbolo": "Nh",
        "grupo": 13,
        "periodo": 7,
        "nombreAlimento": "Nachos",
        "grupoNutricional": "Botanas",
        "valorNutricional": "100-200 kcal por porción (varía según los ingredientes), alto en grasas y carbohidratos",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 114,
        "elemento": "Flerovio",
        "simbolo": "Fl",
        "grupo": 14,
        "periodo": 7,
        "nombreAlimento": "Flan",
        "grupoNutricional": "Postres",
        "valorNutricional": "300-500 kcal por porción (varía según los ingredientes), alto en grasas y carbohidratos",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 115,
        "elemento": "Moscovio",
        "simbolo": "Mc",
        "grupo": 15,
        "periodo": 7,
        "nombreAlimento": "Macarrones",
        "grupoNutricional": "Pastas",
        "valorNutricional": "300-500 kcal por porción (varía según los ingredientes), alto en grasas y carbohidratos",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"        
    },
    {
        "numeroAtomico": 116,
        "elemento": "Livermorio",
        "simbolo": "Lv",
        "grupo": 16,
        "periodo": 7,
        "nombreAlimento": "Oliva",
        "descripcion": "Oliva (aceituna)",
        "grupoNutricional": "Frutas",
        "valorNutricional": "1 g de proteínas, 0.2 g de grasas, 10 g de carbohidratos, 3 g de fibra, 50 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 50,
        "proteinas": 1,
        "grasas": 0.2,
        "carbohidratos": 10,
        "fibra": 3,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"        
    },
    {
        "numeroAtomico": 117,
        "elemento": "Tenesino",
        "simbolo": "Ts",
        "grupo": 17,
        "periodo": 7,
        "nombreAlimento": "Tostadas",
        "grupoNutricional": "Panadería",
        "valorNutricional": "100-200 kcal por porción (varía según los ingredientes), alto en grasas y carbohidratos",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"        
    },
    {
        "numeroAtomico": 118,
        "elemento": "Oganesón",
        "simbolo": "Og",
        "grupo": 18,
        "periodo": 7,
        "nombreAlimento": "Orégano",
        "grupoNutricional": "Hierbas",
        "valorNutricional": "0 kcal por 100 g, sin grasas, carbohidratos ni proteínas",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 0,
        "proteinas": 0,
        "grasas": 0,
        "carbohidratos": 0,
        "fibra": 0,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "periodo": 9
    },
    {
        "numeroAtomico": 57,
        "elemento": "Lantano",
        "simbolo": "La",
        "grupo": 3,
        "periodo": 9,
        "nombreAlimento": "Langosta",
        "grupoNutricional": "Mariscos",
        "valorNutricional": "20 g de proteínas, 5 g de grasas, 0 g de carbohidratos, 0 g de fibra, 120 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 120,
        "proteinas": 20,
        "grasas": 5,
        "carbohidratos": 0,
        "fibra": 0,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"        
    },    
    {
        "numeroAtomico": 58,
        "elemento": "Cerio",
        "simbolo": "Ce",
        "grupo": 3,
        "periodo": 9,
        "nombreAlimento": "Crema",
        "grupoNutricional": "Lácteos",
        "valorNutricional": "5 g de proteínas, 10 g de grasas, 2 g de carbohidratos, 1 g de fibra, 150 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 59,
        "elemento": "Praseodimio",
        "simbolo": "Pr",
        "grupo": 3,
        "periodo": 9,
        "nombreAlimento": "Pretzel",
        "grupoNutricional": "Botanas",
        "valorNutricional": "100-200 kcal por porción (varía según los ingredientes), alto en grasas y carbohidratos",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 60,
        "elemento": "Neodimio",
        "simbolo": "Nd",
        "grupo": 3,
        "periodo": 9,
        "nombreAlimento": "Mandioca",
        "descripcion": "Mandioca (Yuca)",
        "grupoNutricional": "Tubérculos",
        "valorNutricional": "5 g de proteínas, 10 g de grasas, 2 g de carbohidratos, 1 g de fibra, 150 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 61,
        "elemento": "Prometio",
        "simbolo": "Pm",
        "grupo": 3,
        "periodo": 9,
        "nombreAlimento": "Pimientos",
        "grupoNutricional": "Verduras",
        "valorNutricional": "1 g de proteínas, 0.2 g de grasas, 10 g de carbohidratos, 3 g de fibra, 50 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 50,
        "proteinas": 1,
        "grasas": 0.2,
        "carbohidratos": 10,
        "fibra": 3,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 62,
        "elemento": "Samario",
        "simbolo": "Sm",
        "grupo": 3,
        "periodo": 9,
        "nombreAlimento": "Semosas",
        "grupoNutricional": "Botanas",
        "valorNutricional": "100-200 kcal por porción (varía según los ingredientes), alto en grasas y carbohidratos",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 63,
        "elemento": "Europio",
        "simbolo": "Eu",
        "grupo": 3,
        "periodo": 9,
        "nombreAlimento": "Eucalipto",
        "grupoNutricional": "Frutas",
        "valorNutricional": "1 g de proteínas, 0.2 g de grasas, 10 g de carbohidratos, 3 g de fibra, 50 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 50,
        "proteinas": 1,
        "grasas": 0.2,
        "carbohidratos": 10,
        "fibra": 3,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 64,
        "elemento": "Gadolinio",
        "simbolo": "Gd",
        "grupo": 3,
        "periodo": 9,   
        "nombreAlimento": "Gindilla",
        "descripcion": "Gindilla (Chile)",
        "grupoNutricional": "Verduras",
        "valorNutricional": "1 g de proteínas, 0.2 g de grasas, 10 g de carbohidratos, 3 g de fibra, 50 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 50,
        "proteinas": 1,
        "grasas": 0.2,
        "carbohidratos": 10,
        "fibra": 3,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"        
    },
    {
        "numeroAtomico": 65,
        "elemento": "Terbio",
        "simbolo": "Tb",
        "grupo": 3,
        "periodo": 9,
        "nombreAlimento": "Tortilla batata",
        "grupoNutricional": "Leguminosas",
        "valorNutricional": "5 g de proteínas, 10 g de grasas, 2 g de carbohidratos, 1 g de fibra, 150 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 66,
        "elemento": "Disprosio",
        "simbolo": "Dy",
        "grupo": 3,
        "periodo": 9,
        "nombreAlimento": "Candy",
        "descripcion": "Candy (Caramelo)",
        "grupoNutricional": "Botanas",
        "valorNutricional": "100-200 kcal por porción (varía según los ingredientes), alto en grasas y carbohidratos",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 67,
        "elemento": "Holmio",
        "simbolo": "Ho",
        "grupo": 3,
        "periodo": 9,
        "nombreAlimento": "Hot Cakes",
        "grupoNutricional": "Panadería",
        "valorNutricional": "100-200 kcal por porción (varía según los ingredientes), alto en grasas y carbohidratos",
        "beneficios": "Ayuda a la formación de tejidos y músculos", 
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 68,
        "elemento": "Erbio",
        "simbolo": "Er",
        "grupo": 3,
        "periodo": 9,
        "nombreAlimento": "Erizo",
        "grupoNutricional": "Mariscos",
        "valorNutricional": "20 g de proteínas, 5 g de grasas, 0 g de carbohidratos, 0 g de fibra, 120 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 120,
        "proteinas": 20,
        "grasas": 5,
        "carbohidratos": 0,
        "fibra": 0,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"        
    },
    {
        "numeroAtomico": 69,
        "elemento": "Tulio",
        "simbolo": "Tm",
        "grupo": 3,
        "periodo": 9,
        "nombreAlimento": "Tamales",
        "grupoNutricional": "Comida rápida",
        "valorNutricional": "300-500 kcal por porción (varía según los ingredientes), alto en grasas y carbohidratos",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"        
    },
    {
        "numeroAtomico": 70,
        "elemento": "Iterbio",
        "simbolo": "Yb",
        "grupo": 3,
        "periodo": 9,
        "nombreAlimento": "Yuba",
        "descripcion": "Yuba (piel de tofu)",
        "grupoNutricional": "Leguminosas",
        "valorNutricional": "5 g de proteínas, 10 g de grasas, 2 g de carbohidratos, 1 g de fibra, 150 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 71,
        "elemento": "Lutecio",
        "simbolo": "Lu",
        "grupo": 3,
        "periodo": 9,
        "nombreAlimento": "Lúgano",
        "descripcion": "Lúgano (pescado)",
        "grupoNutricional": "Pescados",
        "valorNutricional": "20 g de proteínas, 5 g de grasas, 0 g de carbohidratos, 0 g de fibra, 120 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 120,
        "proteinas": 20,
        "grasas": 5,
        "carbohidratos": 0,
        "fibra": 0,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"        
    },
    {"periodo": 9},
    {"periodo": 9},
    {
        "periodo": 10,
    },
    {
        "numeroAtomico": 89,
        "elemento": "Actinio",
        "simbolo": "Ac",
        "grupo": 3,
        "periodo": 10,
        "nombreAlimento": "Acelgas",
        "grupoNutricional": "Verduras",
        "valorNutricional": "1 g de proteínas, 0.2 g de grasas, 10 g de carbohidratos, 3 g de fibra, 50 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 50,
        "proteinas": 1,
        "grasas": 0.2,
        "carbohidratos": 10,
        "fibra": 3,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 90,
        "elemento": "Torio",
        "simbolo": "Th",
        "grupo": 3,
        "periodo": 10,
        "nombreAlimento": "Té Thai",
        "grupoNutricional": "Bebidas",
        "valorNutricional": "50-100 kcal por porción (varía según los ingredientes), alto en grasas y carbohidratos",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 75,
        "proteinas": 1,
        "grasas": 0.5,
        "carbohidratos": 15,
        "fibra": 2,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"        
    },
    {
        "numeroAtomico": 91,
        "elemento": "Protactinio",
        "simbolo": "Pa",
        "grupo": 3,
        "periodo": 10,
        "nombreAlimento": "Patatas",
        "grupoNutricional": "Verduras",
        "valorNutricional": "1 g de proteínas, 0.2 g de grasas, 10 g de carbohidratos, 3 g de fibra, 50 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 50,
        "proteinas": 1,
        "grasas": 0.2,
        "carbohidratos": 10,
        "fibra": 3,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 92,
        "elemento": "Uranio",
        "simbolo": "U",
        "grupo": 3,
        "periodo": 10,
        "nombreAlimento": "Uvas",
        "grupoNutricional": "Frutas",
        "valorNutricional": "1 g de proteínas, 0.2 g de grasas, 10 g de carbohidratos, 3 g de fibra, 50 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 50,
        "proteinas": 1,
        "grasas": 0.2,
        "carbohidratos": 10,
        "fibra": 3,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 93,
        "elemento": "Neptunio",
        "simbolo": "Np",
        "grupo": 3,
        "periodo": 10,
        "nombreAlimento": "Nopales",
        "grupoNutricional": "Verduras",
        "valorNutricional": "1 g de proteínas, 0.2 g de grasas, 10 g de carbohidratos, 3 g de fibra, 50 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 50,
        "proteinas": 1,
        "grasas": 0.2,
        "carbohidratos": 10,
        "fibra": 3,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 94,
        "elemento": "Plutonio",
        "simbolo": "Pu",
        "grupo": 3,
        "periodo": 10,
        "nombreAlimento": "Pulpo",
        "grupoNutricional": "Mariscos",
        "valorNutricional": "20 g de proteínas, 5 g de grasas, 0 g de carbohidratos, 0 g de fibra, 120 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 120,
        "proteinas": 20,
        "grasas": 5,
        "carbohidratos": 0,
        "fibra": 0,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 95,
        "elemento": "Americio",
        "simbolo": "Am",
        "grupo": 3,
        "periodo": 10,
        "nombreAlimento": "Amaranto",
        "grupoNutricional": "Cereales",
        "valorNutricional": "100-200 kcal por porción (varía según los ingredientes), alto en grasas y carbohidratos",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"        
    },
    {
        "numeroAtomico": 96,
        "elemento": "Curio",
        "simbolo": "Cm",
        "grupo": 3,
        "periodo": 10,
        "nombreAlimento": "Camarones",
        "grupoNutricional": "Mariscos",
        "valorNutricional": "20 g de proteínas, 5 g de grasas, 0 g de carbohidratos, 0 g de fibra, 120 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 120,
        "proteinas": 20,
        "grasas": 5,
        "carbohidratos": 0,
        "fibra": 0,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 97,
        "elemento": "Berkelio",
        "simbolo": "Bk",
        "grupo": 3,
        "periodo": 10,
        "nombreAlimento": "Black Tea",
        "descripcion": "Black Tea (Té negro)",
        "grupoNutricional": "Bebidas",
        "valorNutricional": "0 kcal por 100 ml, sin grasas, carbohidratos ni proteínas",
        "beneficios": "Ayuda a la hidratación y a la digestión",
        "riesgos": "Puede causar ahogamiento",
        "calorias": 0,
        "proteinas": 0,
        "grasas": 0,
        "carbohidratos": 0,
        "fibra": 0,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 98,
        "elemento": "Californio",
        "simbolo": "Cf",
        "grupo": 3,
        "periodo": 10,
        "nombreAlimento": "Café",
        "grupoNutricional": "Bebidas",
        "valorNutricional": "0 kcal por 100 ml, sin grasas, carbohidratos ni proteínas",
        "beneficios": "Ayuda a la hidratación y a la digestión",
        "riesgos": "Puede causar ahogamiento",
        "calorias": 0,
        "proteinas": 0,
        "grasas": 0,
        "carbohidratos": 0,
        "fibra": 0,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 99,
        "elemento": "Einstenio",
        "simbolo": "Es",
        "grupo": 3,
        "periodo": 10,
        "nombreAlimento": "Espinacas",
        "grupoNutricional": "Verduras",
        "valorNutricional": "1 g de proteínas, 0.2 g de grasas, 10 g de carbohidratos, 3 g de fibra, 50 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 50,
        "proteinas": 1,
        "grasas": 0.2,
        "carbohidratos": 10,
        "fibra": 3,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 100,
        "elemento": "Fermio",
        "simbolo": "Fm",
        "grupo": 3,
        "periodo": 10,
        "nombreAlimento": "Fecula de maíz",
        "grupoNutricional": "Cereales",
        "valorNutricional": "100-200 kcal por porción (varía según los ingredientes), alto en grasas y carbohidratos",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 101,
        "elemento": "Mendelevio",
        "simbolo": "Md",
        "grupo": 3,
        "periodo": 10,
        "nombreAlimento": "Mandarina",
        "grupoNutricional": "Frutas",
        "valorNutricional": "1 g de proteínas, 0.2 g de grasas, 10 g de carbohidratos, 3 g de fibra, 50 calorías",
        "beneficios": "Ayuda a la digestión y a la salud intestinal",
        "riesgos": "Puede causar alergias",
        "calorias": 50,
        "proteinas": 1,
        "grasas": 0.2,
        "carbohidratos": 10,
        "fibra": 3,
        "vitaminas": "A, B, C",
        "minerales": "Calcio, potasio"
    },
    {
        "numeroAtomico": 102,
        "elemento": "Nobelio",
        "simbolo": "No",
        "grupo": 3,
        "periodo": 10,
        "nombreAlimento": "Centeno",
        "descripcion": "Pan de centeno",
        "grupoNutricional": "Panadería",
        "valorNutricional": "100-200 kcal por porción (varía según los ingredientes), alto en grasas y carbohidratos",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 150,
        "proteinas": 5,
        "grasas": 10,
        "carbohidratos": 2,
        "fibra": 1,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {
        "numeroAtomico": 103,
        "elemento": "Laurencio",
        "simbolo": "Lr",
        "grupo": 3,
        "periodo": 10,
        "nombreAlimento": "Lomo relleno",
        "grupoNutricional": "Carnes",
        "valorNutricional": "20 g de proteínas, 5 g de grasas, 0 g de carbohidratos, 0 g de fibra, 120 calorías",
        "beneficios": "Ayuda a la formación de tejidos y músculos",
        "riesgos": "Puede causar alergias",
        "calorias": 120,
        "proteinas": 20,
        "grasas": 5,
        "carbohidratos": 0,
        "fibra": 0,
        "vitaminas": "A, B, D",
        "minerales": "Hierro, calcio"
    },
    {"periodo": 10},
    {"periodo": 10}    
];
